adminpage/urls.py
from django.urls import path
from . import views

app_name = 'adminpage'

urlpatterns = [
    path('', views.beranda, name='beranda')
]

knowyourswaifu_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('adm/', include('adminpage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.series, name='series'),
    path('login/', views.LoginView, name='login'),
    path('logout/', views.LogoutView, name='logout'),
    path('register/', views.register, name='register'),
    path('series/<int:id>/', views.detail_series, name='detail_series')
]

adminpage/models.py
from django.db import models
from main.models import CustomUser as user
# Create your models here.


def images_directory_path(instance, filename):
    return 'series/{0}/{1}'.format(instance.name, filename)


class admin(models.Model):
    user = models.ForeignKey(user, on_delete=models.CASCADE)
    age = models.IntegerField()

    def __str__(self):
        return self.user.email

    class Meta:
        db_table = 'tabel_admin'


class test_upload(models.Model):
    name = models.CharField(max_length=255, default='as')
    image1 = models.ImageField(upload_to=images_directory_path)
    image2 = models.ImageField(upload_to=images_directory_path)
    image3 = models.ImageField(upload_to=images_directory_path)

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
# Create your models here.

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length = 255)
    last_name = models.CharField(max_length = 255)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_voters = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name']

    object = CustomUserManager()

    def __str__(self):
        return self.email


class SeriesModel(models.Model):
    kode = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=255)
    gambar = models.CharField(max_length=255)
    gambar_header = models.CharField(max_length=255)
    gambar_body = models.CharField(max_length=255)

    def __str__(self):
        return self.nama


class HeroineModel(models.Model):
    kode = models.AutoField(primary_key=True)
    series = models.ForeignKey(SeriesModel, on_delete=models.CASCADE)
    nama = models.CharField(max_length=255)
    birthday = models.CharField(max_length=255)
    height = models.CharField(max_length=255)
    hair_color = models.CharField(max_length=255)
    eye_color = models.CharField(max_length=255)
    voice_actor = models.CharField(max_length=255)
    gambar = models.CharField(max_length=255)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.nama

class Voted(models.Model):
    user = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    series = models.ForeignKey(SeriesModel, on_delete = models.CASCADE)
    choice = models.CharField(max_length = 255)

adminpage/views.py
from django.shortcuts import render
from .models import test_upload
# Create your views here.
def beranda(request):
    print (test_upload.objects.all()[0].image1)
    if request.method == 'POST':
        if request.POST.get('nama'):
            name = request.POST.get('nama')
            foto1 = request.FILES.get('logo')
            foto1.name = 'logo.png'
            foto2 = request.FILES.get('header')
            foto2.name = 'header.png'
            foto3 = request.FILES.get('body')
            foto3.name = 'body.png'
            test_upload.objects.create(name = name ,image1 = foto1, image2 = foto2, image3 = foto3)
    return render(request = request,
                  template_name = 'html/tambah_series.html')

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login
from django.db import IntegrityError
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from .models import SeriesModel, HeroineModel, CustomUser as User, Voted
# Create your views here.

def LoginView(request):
    if request.method == 'POST':
        if request.POST.get('email'):
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(email = email, password = password)
            if user:
                login(request, user)
                return redirect('main:series')
            else:
                messages.error(request, f'Please Check Your Email or Password')
    return render(request = request,
                 template_name = 'html/login.html')

def register(request):
    if request.method == 'POST':
        if request.POST.get('email'):
            password = request.POST.get('pass')
            pass2 = request.POST.get('pass2')
            if password != pass2:
                messages.error(request, f"Password doesn't match")
                return redirect('main:register')
            email = request.POST.get('email')
            first = request.POST.get('first')
            last = request.POST.get('last')
            try:
                User.object.create_user(email, password, first_name = first, last_name = last)
                messages.success(request, f'Registration Success')
                return redirect('main:login')
            except IntegrityError:
                messages.error(request, f'Email already exists.')
                return redirect('main:register')
    return render(request = request,
                 template_name = 'html/register.html')

def LogoutView(request):
    logout(request)
    return redirect('main:login')

def series(request):
    judul = 'List Series'
    kumpulan_data = SeriesModel.objects.all()
    return render(request = request,
                  template_name = 'html/series.html',
                  context={'kumpulan_data': kumpulan_data, 'judul': judul})

def detail_series(request, id):
    seri = get_object_or_404(SeriesModel, pk = id)
    kumpulan_data = HeroineModel.objects.all().filter(series = seri)
    try:
        is_voted = Voted.objects.get(Q(series = seri) & Q(user = request.user))
        heroine = HeroineModel.objects.get(pk = is_voted.choice)
        is_voted.heroine = heroine.nama
    except:
        is_voted = False
    if request.method == 'POST':
        if request.POST.get('heroine_id'):
            kode = request.POST.get('heroine_id')
            heroine = HeroineModel.objects.get(kode = kode)
            heroine.vote += 1
            heroine.save()
            Voted.objects.create(series = seri, user = request.user, choice = kode)
            messages.success(request, 'Vote Success')
            return redirect('main:detail_series', id)
        else:
            messages.error(request, 'Please Choose Heroine First Before Vote!')
    return render(request = request,
                  template_name = 'html/detail_series.html',
                  context= {'kumpulan_data': kumpulan_data, 'seri': seri, 'is_voted': is_voted})

adminpage/templates/html/base_adminpage.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ARS School | {% block judul%}{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'css/adminlte/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />

</head>

<body class="hold-transition sidebar-mini layout-boxed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'main:logout' %}" class="nav-link btn btn-default btn-flat" style="cursor: pointer;">Logout</a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->

        {% include 'html/sidebar.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                {% include 'html/messages.html' %}
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-12">
                            <h1 class="text-center">{{judul}}</h1>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                {% block konten %}

                {% endblock %}
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.0.1
            </div>
            <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
            reserved.
        </footer> -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'plugins/chart.js/Chart.min.js'%}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'js/adminlte/adminlte.js'%}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <!-- <script src="{% static 'js/adminlte/pages/dashboard.js'%}"></script> -->
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'js/adminlte/demo.js' %}"></script>
    <script>
        var salesChartCanvas = document.getElementById('revenue-chart-canvas').getContext('2d');
        //$('#revenue-chart').get(0).getContext('2d');

        // Donut Chart
        var pieChartCanvas = $('#sales-chart-canvas').get(0).getContext('2d')
        var labelData = {{data.tahun}}
        var dataLaki = {{data.laki_all}}
        var dataPerempuan = {{data.perempuan_all}}
        var pieData = {
            labels: [
                "Laki-Laki",
                "Perempuan"
            ],
        datasets: [
            {
                data: [{{data.laki|safe}}, {{data.perempuan|safe}}],
                backgroundColor: ['#00a65a', '#f0ad4e'],
            }
        ]
        }
        var pieOptions = {
            legend: {
                display: true
            },
            maintainAspectRatio: false,
            responsive: true,
        }
        //Create pie or douhnut chart
        // You can switch between pie and douhnut using the method below.
        var salesChart = new Chart(salesChartCanvas, {
            type: 'doughnut',
            data: pieData,
            options: pieOptions
        });

        // Sales graph chart
        var salesGraphChartCanvas = $('#line-chart').get(0).getContext('2d');
        //$('#revenue-chart').get(0).getContext('2d');

        var salesGraphChartData = {
            labels: labelData,
            datasets: [
                {
                    label: 'Laki-Laki',
                    fill: false,
                    borderWidth: 2,
                    lineTension: 0,
                    spanGaps: true,
                    borderColor: '#80ffa6',
                    pointRadius: 3,
                    pointHoverRadius: 7,
                    pointColor: '#efefef',
                    pointBackgroundColor: '#efefef',
                    data: dataLaki
                },
                {
                    label: 'Perempuan',
                    fill: false,
                    borderWidth: 2,
                    lineTension: 0,
                    spanGaps: true,
                    borderColor: '#f0ad4e',
                    pointRadius: 3,
                    pointHoverRadius: 7,
                    pointColor: '#efefef',
                    pointBackgroundColor: '#efefef',
                    data: dataPerempuan
                }
            ]
        }

        var salesGraphChartOptions = {
            maintainAspectRatio: false,
            responsive: true,
            legend: {
                display: false,
            },
            scales: {
                xAxes: [{
                    ticks: {
                        fontColor: '#efefef',
                    },
                    gridLines: {
                        display: false,
                        color: '#efefef',
                        drawBorder: false,
                    }
                }],
                yAxes: [{
                    ticks: {
                        stepSize: 5000,
                        fontColor: '#efefef',
                    },
                    gridLines: {
                        display: true,
                        color: '#efefef',
                        drawBorder: false,
                    }
                }]
            }
        }

        // This will get the first returned node in the jQuery collection.
        var salesGraphChart = new Chart(salesGraphChartCanvas, {
            type: 'line',
            data: salesGraphChartData,
            options: salesGraphChartOptions
        }
        )
    </script>


    <script type="text/javascript">
        $(function () {
            $('#datetimepicker5').datetimepicker({
                format: 'DD-MM-YYYY'
            });
        });
    </script>
</body>

</html>

adminpage/templates/html/beranda.html
{% extends 'html/base_adminpage.html'%}

{% block judul %}Beranda{%endblock%}

{% block konten %}
<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>0</h3>

                    <p>Jumlah Siswa Yang Mendaftar</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person"></i>
                </div>
                
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>0</h3>

                    <p>Laki-Laki</p>
                </div>
                <div class="icon">
                    <i class="ion ion-male"></i>
                </div>
                
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>0</h3>

                    <p>Perempuan</p>
                </div>
                <div class="icon">
                    <i class="ion ion-female"></i>
                </div>
                
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>0</h3>

                    <p>Nilai Rata-rata Siswa</p>
                </div>
                <div class="icon">
                    <i class="ion ion-calculator"></i>
                </div>
                
            </div>
        </div>
        <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-7 connectedSortable">
            <!-- Custom tabs (Charts with tabs)-->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-chart-pie mr-1"></i>
                        Bagan Siswa yang mendaftar berdasarkan jenis kelamin
                    </h3>
                </div><!-- /.card-header -->
                <div class="card-body">
                    <div class="tab-content p-0">
                        <!-- Morris chart - Sales -->
                        <div class="chart tab-pane active" id="revenue-chart"
                            style="position: relative; height: 300px;">
                            <canvas id="revenue-chart-canvas" height="300" style="height: 300px;"></canvas>
                        </div>
                        <div class="chart tab-pane" id="sales-chart" style="position: relative; height: 300px;">
                            <canvas id="sales-chart-canvas" height="300" style="height: 300px;"></canvas>
                        </div>
                    </div>
                </div><!-- /.card-body -->
            </div>
            <!-- /.card -->

        </section>
        <!-- /.Left col -->
        <!-- right col (We are only adding the ID to make the widgets sortable)-->
        <section class="col-lg-5 connectedSortable">

            <!-- solid sales graph -->
            <div class="card bg-gradient-info">
                <div class="card-header border-0">
                    <h3 class="card-title">
                        <i class="fas fa-th mr-1"></i>
                        Grafik Siswa yang mendaftar
                    </h3>
                </div>
                <div class="card-body">
                    <canvas class="chart" id="line-chart"
                        style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                </div>
                <!-- /.card-body -->

                <!-- /.card-footer -->
            </div>
            <!-- /.card -->

        </section>
        <!-- right col -->
    </div>
    <!-- /.row (main row) -->
    
</div>
{% endblock %}

adminpage/templates/html/sidebar.html
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
        <img src="https://i.postimg.cc/qqfG9SZm/Admin-LTELogo.png" alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">ARS School</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="https://i.postimg.cc/05fqkXR8/user2-160x160.jpg" class="img-circle elevation-2"
                    alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{name}}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link {%if active == 'beranda'%}active{%endif%}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Beranda</p>
                    </a>
                </li>
                <li class="nav-item has-treeview {%if active == 'semua' or active == 'kelas'%}menu-open{%endif%}">
                    <a href="#" class="nav-link {%if active == 'semua' or active == 'kelas'%}active{%endif%}">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            List Siswa
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link {%if active == 'semua'%}active{%endif%}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Semua Siswa</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link {%if active == 'kelas'%}active{%endif%}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Berdasarkan Kelas</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link {%if active == 'penentuan'%}active{%endif%}">
                        <i class="nav-icon fas fa-clipboard"></i>
                        <p>Penentuan Kelas Otomatis</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link {%if active == 'tambah'%}active{%endif%}">
                        <i class="nav-icon fas fa-user-plus"></i>
                        <p>Tambah Siswa</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link {%if active == 'register'%}active{%endif%}">
                        <i class="nav-icon fas fa-user-shield"></i>
                        <p>Tambah Admin</p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link {%if active == 'pilih_soal'%}active{%endif%}">
                        <i class="nav-icon fas fa-pen"></i>
                        <p>Soal Test</p>
                    </a>
                </li>
                <li class="nav-item has-treeview {%if active == 'set_tahun' or active == 'tambah_tahun'%}menu-open{%endif%}">
                    <a href="#" class="nav-link {%if active == 'set_tahun' or active == 'tambah_tahun'%}active{%endif%}">
                        <i class="nav-icon fas fa-cog"></i>
                        <p>
                            Tahun Ajaran
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link {%if active == 'set_tahun'%}active{%endif%}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Setting Tahun Ajaran</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link {%if active == 'tambah_tahun'%}active{%endif%}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Tahun Ajaran Baru</p>
                            </a>
                        </li>
                        </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

adminpage/templates/html/tambah_series.html
{% extends 'html/base_adminpage.html' %}

{%block judul%}Tambah Siswa{%endblock%}

{% block konten %}
<div class="container">
    <br>
    <div class="row justify-content-center">
        <div class="form-group bg-success col-6">
            <form method="POST" enctype="multipart/form-data">
                {%csrf_token%}
                <div class="form-group">
                    <label>Nama Series</label>
                    <input type="text" class="form-control" name="nama" placeholder="Masukan Nama Series" required>
                    <!-- <div class="form-group row mt-2">
                        <label class="col-sm-12 col-5 pt-2">Tahun Ajaran</label>
                        <select class="form-control col-sm-12 col-5" name="tahun">
                            {% for tahun in tahun %}
                            <option value="{{tahun}}">{{tahun.thn}}</option>
                            {% endfor %}
                        </select>
                    </div> -->
                    <label>Foto Logo</label>
                    <input type="file" class="form-control bg-success mb-4" name="logo" required>
                    <label>Foto Header</label>
                    <input type="file" class="form-control bg-success mb-4" name="header" required>
                    <label>Foto Body</label>
                    <input type="file" class="form-control bg-success mb-4" name="body" required>
                    <div class="form-group row">
                        <input type="reset" class="form-control btn btn-danger col" value="Reset">
                        <input type="submit" class="form-control btn btn-primary col" value="Tambah">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/html/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static%}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title%}{% endblock%}</title>
</head>

<body style="background-image: url({% block gambar_body%}{% endblock %});">
    <div class="header"
        style="background-size: 100% 100%;background-image: url({%block gambar_header %}{% endblock %})">
        <div class="row">
            <div class="col-12 navbar navbar-expand-lg">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ml-lg-auto">
                    <li class="nav-item navigasi">
                        <a href="#" class="nav-link" style="font-size: 30px;">Home</a>
                    </li>
                    <li class="nav-item navigasi aktif">
                        <a href="#" class="nav-link" style="font-size: 30px;">Series</a>
                    </li>
                    <li class="nav-item navigasi">
                        <a href="#" class="nav-link" style="font-size: 30px;">Favorite</a>
                    </li>
                </ul>
            </div>
            <div class="login_group">
                {% if user.is_authenticated%}
                <a href="{% url 'main:logout' %}">
                    <button class="btn btn-primary mr-2 mt-3 button_header">Logout</button>
                </a>
                {% else %}
                <a href="{% url 'main:login' %}">
                    <button class="btn btn-primary mr-2 mt-3 button_header">Login</button>
                </a>
                <a href="{% url 'main:register' %}">
                    <button class="btn btn-primary mr-2 mt-3 button_header">Register</button>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% block konten%}

    {% endblock %}

    <script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    {% if user.is_authenticated and is_voted%}
    <script type="text/javascript">
        $(window).on('load', function () {
            var id = {{is_voted.choice}}
            var box = document.getElementById(id)
            var allBox = document.getElementsByName('box')
            for (i = 0; i < allBox.length; i++) {
                allBox[i].style.filter = 'grayscale(100%)'
                allBox[i].style.cursor = 'auto'
            }
            box.style.filter = 'grayscale(0%)'
        });
    </script>
    {% endif %}
</body>

</html>